govuk-one-login/ipv-cri-fraud-api

.github/pull_request_template.md, .github/workflows/build.yml, .gitignore, README.md, build.gradle, deploy.sh, deploy/api.yaml, deploy/template.yaml, gradle/wrapper/gradle-wrapper.properties, lambdas/accesstoken/build.gradle, lambdas/accesstoken/src/main/java/uk/gov/di/ipv/cri/fraud/api/handler/AccessTokenHandler.java, lambdas/accesstoken/src/main/java/uk/gov/di/ipv/cri/fraud/api/handler/client authentication.http, lambdas/accesstoken/src/test/java/uk/gov/di/ipv/cri/fraud/api/handler/AccessTokenHandlerTest.java, lib/build.gradle, lib/src/main/java/uk/gov/di/ipv/cri/fraud/library/annotations/ExcludeFromGeneratedCoverageReport.java, lib/src/main/java/uk/gov/di/ipv/cri/fraud/library/error/ErrorResponse.java, lib/src/main/java/uk/gov/di/ipv/cri/fraud/library/exception/AccessTokenProcessingException.java, lib/src/main/java/uk/gov/di/ipv/cri/fraud/library/exception/AccessTokenValidationException.java, lib/src/main/java/uk/gov/di/ipv/cri/fraud/library/helpers/ApiGatewayResponseGenerator.java, lib/src/main/java/uk/gov/di/ipv/cri/fraud/library/helpers/RequestHelper.java, lib/src/main/java/uk/gov/di/ipv/cri/fraud/library/persistence/DataStore.java, lib/src/main/java/uk/gov/di/ipv/cri/fraud/library/persistence/item/AccessTokenItem.java, lib/src/main/java/uk/gov/di/ipv/cri/fraud/library/service/AccessTokenService.java, lib/src/main/java/uk/gov/di/ipv/cri/fraud/library/service/ConfigurationService.java, lib/src/main/java/uk/gov/di/ipv/cri/fraud/library/validation/ValidationResult.java, lib/src/test/java/uk/gov/di/ipv/cri/fraud/library/helpers/RequestHelperTest.java, lib/src/test/java/uk/gov/di/ipv/cri/fraud/library/persistance/DataStoreTest.java, lib/src/test/java/uk/gov/di/ipv/cri/fraud/library/service/AccessTokenServiceTest.java, lib/src/test/java/uk/gov/di/ipv/cri/fraud/library/service/ConfigurationServiceTest.java, settings.gradle
Add a Access Token Request lambda and API resource for the Fraud CRI.
Get this running in the dev CRI account by following instructions in the README.md.
See RFC https://github.com/alphagov/digital-identity-architecture/pull/84 for an explanation of the Client Credentials Grant used in this CRI.
- [KBV-157](https://govukverify.atlassian.net/browse/KBV-157)
=> KBV-157 Access Token resource

infrastructure/lambda/api.yaml, infrastructure/lambda/template.yaml, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/handler/FraudHandler.java, lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/handler/CredentialHandlerTest.java, settings.gradle
Added authorization lambda to the api and template yamls 
Add code to generate and save the authorisation code
Token resource needed an authroization code saved to the session in order to successfully generate the token
- [KBV-157](https://govukverify.atlassian.net/browse/KBV-157)
=> KBV-157: Changes to enable the E2E Fraud journey

.github/workflows/post-merge-package-for-build.yml, acceptance-tests/Dockerfile, acceptance-tests/result.json, acceptance-tests/run-tests.sh
acceptance tests added to package-for-build
To pass test stage of pipeline build. The test pack is skeletal
- [KBV-487](https://govukverify.atlassian.net/browse/KBV-487)
=> [KBV-487] acceptance tests added to package-for-build

infrastructure/lambda/template.yaml
Updating param store permissions to have env prefix
=> KBV-487: Updating template to ue third party crdentials with env prefix

infrastructure/lambda/template.yaml
API Gateway ID export
API Gateway ID exported
API Gateway ID needed for fraud frontend deployment
- [KBV-447](https://govukverify.atlassian.net/browse/KBV-447)
=> [KBV-447] Export API Gateway ID for frontend fargate migration

infrastructure/lambda/template.yaml
Updating template to work with integration frontend pre dns
To enable integration testin in int
=> KBV-502: Updating template to work with integration frontend pre dns

infrastructure/lambda/template.yaml
Reverting integration audience
Reverting after debugging issue
=> KBV-502: Reverted changed to audience in templates

lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/handler/FraudHandler.java, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/fraud/api/domain/Evidence.java, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/fraud/api/domain/ThirdPartyAddress.java, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/VerifiableCredentialService.java
Fixed issue with field not being ignored in VC mapper
Added missing txn field
=> KBV-502: Fixed issue with values not being ignored in VC mapper

infrastructure/lambda/template.yaml, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/fraud/api/handler/IssueCredentialHandler.java
Updated the common code
Moved to fargate DNS addresses
Move to fargate DNS addresses
- [KBV-553](https://govukverify.atlassian.net/browse/KBV-553)
=> KBV-553: Updting common code and moving to the fargate DNS addresses

infrastructure/lambda/template.yaml
Updated signing key and audience url for prod
The values were not previously set
- [KBV-561](https://govukverify.atlassian.net/browse/KBV-561)
=> KBV-561: Corecting template values for fraud in production

infrastructure/lambda/template.yaml
Updating acceptance test reference
Added stack name to outputs so its available in test
Updating acceptance test reference
Added stack name to outputs so its available in test
=> KBV-538: Updating acceptance test reference

lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/fraud/api/handler/IssueCredentialHandlerTest.java
Added IssueCredentialHandlerTest.
Code is based on the IssueCredentialHandler from Address API, with modifications for Fraud API.
Fraud IssueCredentialHandler had no unit test coverage.
- [KBV-770](https://govukverify.atlassian.net/browse/KBV-770)
=> KBV-770 Add Unit test for IssueCredentialHandler

.github/workflows/post-merge-package-for-build.yml
Update to push test image to staging
To unblock the deployment pipeline
=> LIME-25: Updating build to include pushing to staging

lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationRequestMapper.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationResponseMapper.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGateway.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/request/Application.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/request/Control.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/request/Payload.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/request/Person.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/request/PersonDetails.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/request/ProductDetails.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/handler/FraudHandler.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/ConfigurationService.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/ContraIndicatorRemoteMapper.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationInfoResponseValidator.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationService.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/ServiceFactory.java
Added mapper for PEPRequest/response
To map person Identity to new PEPRequest
=> LIME-37 - Mapping personIdentity to PEPRequest

lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationRequestMapperTest.java, lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationResponseMapperTest.java, lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/util/TestDataCreator.java
- added tests
- minor refactors
- [LIME-37](https://govukverify.atlassian.net/browse/LIME-37)
=> LIME-37 - PEP mapping  tests

lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGatewayTest.java
- added tests PEP error checks
- [LIME-5](https://govukverify.atlassian.net/browse/LIME-5)
=> LIME-5 - Managing errors from PEP

lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGateway.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationService.java
Minor logging update to make tracking pep easier
To help track PEP journeys
- [LIME-35](https://govukverify.atlassian.net/browse/LIME-35)
=> LIME-35: Added additional logs for pep

infrastructure/lambda/template.yaml
Add new csls log subscription endpoints
To enable logging in splunk after existing endpoints are turned off
- [LIME-190](https://govukverify.atlassian.net/browse/LIME-190)
=> LIME-190: Added new python csls endpoints

infrastructure/lambda/template.yaml
Add new csls log subscription endpoints
To enable logging in splunk after existing endpoints are turned off
- [LIME-190](https://govukverify.atlassian.net/browse/LIME-190)
=> LIME-190: Added comments on components to be deprecated

.github/workflows/post-merge-deploy-to-dev.yml, .github/workflows/post-merge-package-for-build.yml, .github/workflows/pre-merge-integration-test.yml, .gitmodules, README.md, build.gradle, deploy.sh, infrastructure/lambda/private-api.yaml, infrastructure/lambda/public-api.yaml, infrastructure/lambda/template.yaml, lambdas/fraudcheck/build.gradle, lambdas/issuecredential/build.gradle, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/VerifiableCredentialService.java, settings.gradle
- Removed git submodules
- Updated github workflows to not checkout submodules
- Added new parameter overrides to the `pre-merge-integration-tests` workflow
- Referenced the `cri-common-lib` jar
- Updated the private/public api configuration to refer to the new common lambda functions
- Removed common resources from `template.yaml`
- Updated `template.yaml` to refer to common resources where necessary
- Updated `VerifiableCredentialService` to refer to new common `verifiableCredentialKmsSigningKeyId` SSM parameter
- To migrate to the common CRI framework and align with the kbv & address CRIs
- [OJ-988](https://govukverify.atlassian.net/browse/OJ-988)
=> Oj 988 transition to new common framework

infrastructure/lambda/private-api.yaml, infrastructure/lambda/template.yaml
Updated api descriptions
To trigger api re deploy so metrics can be read in cloudwatch
=> LIME-191: Minor updates to trigger api to redeploy so that metrics can be read per api

infrastructure/lambda/template.yaml
Added alarm config to the template
Core infra wasnt being updated when deployed and so was not picking up the changes in the parameter value
- [LIME-191](https://govukverify.atlassian.net/browse/LIME-191)
=> LIME-191: Adding config for alarms to fraud 

.github/workflows/pre-merge-integration-test.yml, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/domain/FraudCheckResult.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationResponseMapper.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGateway.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationService.java, lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationResponseMapperTest.java
Added decision score to fraud results
Increased logging
To allow better decision making for no file found fraud cases
=> LIME-253: Adding decision score to fraudcheck result and increasing logging

infrastructure/lambda/template.yaml
Added missing permissions
To fix template errors
=> LIME-248: Adding missing ssm permissions

lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationService.java, lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationServiceTest.java
Added conditional on file found around the PEP check logic
As a user who is not found can never exceed a score of 1 so a pep check is not required
=> LIME-248: Skipping PEP check if file not found as a score of 1 can not be exceeded

infrastructure/lambda/template.yaml
Reintroducing pager duty url
To get around pager duty dependency conflict
=> OJ-1000: Adding pager duty endpoint

infrastructure/lambda/template.yaml, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/VerifiableCredentialService.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/VerifiableCredentialServiceTest.java
- Expiry time increased from 2 hours to 6 months
- [LIME-243](https://govukverify.atlassian.net/browse/LIME-243)
=> LIME-243 - Extend VC Validity to 6 months

.github/workflows/build-image.yml
Updated context to ensure image is pushed from within acceptance tests
Because docker file could not be found
=> LIME-117: Added context as dockerfile could not be found

.github/workflows/build-image.yml
Fixed errors in docker run command and added env vars
To fix error where file should not be passed to run as it is already used in build
=> LIME-117: Fixing errors in docker run command

acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/FraudAPIPage.java, acceptance-tests/src/test/java/gov/di_ipv_fraud/service/ConfigurationService.java, acceptance-tests/src/test/java/gov/di_ipv_fraud/step_definitions/FraudAPIStepDefs.java, acceptance-tests/src/test/resources/features/FraudCRIAPI.feature
Move the API logic from the Step definition files to Page Object classes
This pull request consists of the changes that were made as part of this ticket https://govukverify.atlassian.net/browse/LIME-332
Refactored the Acquire initial JWT tests to move the API logic from the step definition file to the page object file.
=> Move PR - LIME 332 - Move api logic from Step Defs file to page object file

acceptance-tests/run-tests.sh, acceptance-tests/src/test/resources/features/FraudCRI.feature
- `set -e` added back in to test bash file.
- [LIME-335](https://govukverify.atlassian.net/browse/LIME-335)
=> LIME-335 - Revert run-tests.sh change.

.github/workflows/dailySmokeTest.yml
Adding Allure workflow steps to dailySmokeTest.yml file
=> adding Allure workflow steps to dailySmokeTest.yml file

.github/workflows/dailySmokeTest.yml
Changed the Contents permission to 'write' in dailySmokeTest.yml file.
=> LIME-434-updating contents permission to write

acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/FraudPageObject.java, acceptance-tests/src/test/java/gov/di_ipv_fraud/service/ConfigurationService.java, acceptance-tests/src/test/resources/features/FraudCRI.feature
Added dev as an accepted test environment and updated tests to pull in the specified environment instead of always running against build
To run tests in local dev
=> LIME-444 - Updates to run tests in local dev

.github/workflows/dailySmokeTest.yml
Modified the path to the Allure Results folder on the Github workflow steps 'Allure Report action' and 'Deploy report to Github Pages'. 
Changed the path of allure-results from 'acceptance-tests/target/allure-results' to 'target/allure-results' and allure-history from 'acceptance-tests/target/allure-history' to 'target/allure-history'
=> LIME-453-Update-AllureResults-path-in-DailySmokeTest-workflows

.github/workflows/dailySmokeTest.yml
Commenting out the Allure workflow steps in dailySmokeTest.yml
=> Commented out Allure workflow steps

.github/workflows/post-merge-deploy-to-dev.yml, .github/workflows/post-merge-package-for-build.yml, acceptance-tests/Dockerfile, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/response/ClientResponsePayload.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/response/IdentityVerificationResponse.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/response/ResponseHeader.java
Pinned gradle version and set clientResponsePayload to ignore unkown fields in response
=> LIME-468 - Pinning gradle version to fix github actions

acceptance-tests/README.md, acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/FraudAPIPage.java, acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/FraudPageObject.java, acceptance-tests/src/test/java/gov/di_ipv_fraud/step_definitions/FraudStepDefs.java, acceptance-tests/src/test/resources/features/FraudCRI.feature
Renamed Experian in Fraud tests to ThirdParty
=> LIME-464 - Renamed Experian in test to ThirdParty

lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationResponseMapper.java, lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationResponseMapperTest.java
Date format for activity history score fields in third party response
=> LIME-468 - Activity History Score date format test

acceptance-tests/src/test/java/gov/di_ipv_fraud/utilities/Driver.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/domain/FraudCheckResult.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/domain/IdentityVerificationResult.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationResponseMapper.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/handler/FraudHandler.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/ActivityHistoryScoreCalculator.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationService.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/ServiceFactory.java, lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationResponseMapperTest.java, lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/handler/CredentialHandlerTest.java, lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/ActivityHistoryScoreCalculatorTest.java, lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationServiceTest.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/fraud/api/handler/IssueCredentialHandlerTest.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/VerifiableCredentialServiceTest.java, lib/src/main/java/uk/gov/di/ipv/cri/fraud/library/persistence/item/FraudResultItem.java
Added functionality that calculates activity history score
=> LIME-545 - Calculating activity history score

acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/FraudPageObject.java, acceptance-tests/src/test/java/gov/di_ipv_fraud/step_definitions/FraudStepDefs.java, acceptance-tests/src/test/resources/features/FraudCRI.feature
Updated tests to account for expiry field removal
=> LIME-567: Updated tests to account for removed expiry field

.github/workflows/dailySmokeTest.yml, .github/workflows/gradleBuildTest.yml, .github/workflows/post-merge-deploy-to-dev.yml, .github/workflows/post-merge-package-for-build.yml, .github/workflows/pre-merge-integration-test.yml
Updated pinned gradle versions for github actions
=> Update gradle version from 7.3 to 7.6

lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGateway.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/util/SleepHelper.java, lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGatewayTest.java, lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/util/SleepHelperTest.java
Replaces use of Thread.sleep() with a busy wait.
Corrects the first attempt never being ~0ms, due to using 2^tryCount.
Corrects limit value calculated for HTTP_RETRY_WAIT_TIME_LIMIT_MS to 6.4 seconds.
Added unit test using real sleep helper.
The context switch caused by Thread.sleep in a Lambda is a suspect in API response times being unstable.
The replacement of an equivalent busy wait is a test to determine if the context switch is the source with the reschedule not dependable.
Due to using tryCount directly the first attempt was always delayed 100ms. (2^0*100)
The max allowed backoff time was off by 1 power - wait is before send, with a 0ms wait on first try intended, then increasing exponentially from 100 at retry attempt 1..7
SleepHelper is mocked in the thirdparty gateway tests due …
=> LIME-238 Investigate api gateway latency

acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/FraudPageObject.java, acceptance-tests/src/test/java/gov/di_ipv_fraud/step_definitions/FraudStepDefs.java, acceptance-tests/src/test/java/gov/di_ipv_fraud/step_definitions/UniversalStepDefs.java, acceptance-tests/src/test/java/gov/di_ipv_fraud/utilities/BrowserUtils.java, acceptance-tests/src/test/resources/features/FraudCRI.feature, acceptance-tests/src/test/resources/features/WelshLangFraudCRI.feature
Test added to validate the Reject analytics cookies and the correct sentence.
Correct typo in cookeBanner in common-express
[https://govukverify.atlassian.net/browse/LIME-633]
=> Reject Analytics cookie test

acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/FraudAPIPage.java, acceptance-tests/src/test/java/gov/di_ipv_fraud/step_definitions/FraudAPIStepDefs.java, acceptance-tests/src/test/resources/features/FraudCRIAPI.feature
Updated fraud acceptance tests to work with new aws stub
To allow pre merge integration tests to continue to be run
=> LIME-364: Updated tests to work with new stack

infrastructure/lambda/template.yaml
sizing of deployment infrastructure in the cfn template
Updating build configuration to match production for the performance testing 
- [LIME-698](https://govukverify.atlassian.net/browse/LIME-698)
[LIME-698]: https://govukverify.atlassian.net/browse/LIME-698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> lime-698 update scaling for performance testing

infrastructure/lambda/template.yaml
Add Alarm `Private API Gateway Percentage 5XX Errors`
=> Add Alarm for Private API gateway errors above percentage

acceptance-tests/build.gradle
Update `selenium, webdrivermanager and cucumber`
=> Update selenium, webdrivermanager and cucumber

build.gradle
IPS-310 Sonarcloud Migration
IPS-310 Sonarcloud Migration
- [IPS-310 ](https://govukverify.atlassian.net/browse/IPS-310 )
=> IPS-310 Sonarcloud Migration

acceptance-tests/run-tests.sh
Correct test environment used in staging pipeline test step (pipeline changes broken env detection)
- [LIME-844](https://govukverify.atlassian.net/browse/LIME-844)
[LIME-844]: https://govukverify.atlassian.net/browse/LIME-844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-844 Correct test environment used in test step

infrastructure/lambda/template.yaml
- Changed crosscoreV2Enabled parameter to false to turn off route post prod test
=> LIME-921 - PR to toggle off V2 post production test

infrastructure/lambda/template.yaml
Toggle on CrosscoreV2 feature for production testing
=> LIME-921 - PR to toggle on V2 in Prod

infrastructure/lambda/template.yaml
Feature toggling crosscoreV2 off post prod test
=> LIME-921 - PR to toggle off V2

infrastructure/lambda/template.yaml
=> LIME-1012 - Adding dimensions to combined token alarm metrics

.github/dependabot.yml, .github/workflows/build.yml, .github/workflows/dailySmokeTest.yml, .github/workflows/gradleBuildTest.yml, .github/workflows/post-merge-deploy-to-dev.yml, .github/workflows/post-merge-package-for-build.yml, .github/workflows/pre-merge-checks.yml, .github/workflows/pre-merge-integration-test.yml
Update workflows to:
* remove deprecations
* remove rusty actions
* implement dev-platform actions
* add dependabot for workflow actions
The github workflows
* remove deprecations
* remove rusty actions
* implement dev-platform actions
* add dependabot for workflow actions
- [IPS-447](https://govukverify.atlassian.net/browse/IPS-447)
- [IPS-480](https://govukverify.atlassian.net/browse/IPS-480)
- [IPS-503](https://govukverify.atlassian.net/browse/IPS-503)
- 
[IPS-447]: https://govukverify.atlassian.net/browse/IPS-447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-480]: https://govukverify.atlassian.net/browse/IPS-480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-503]: …
=> IPS-477 fix workflow warnings

.github/workflows/post-merge-deploy-to-dev.yml, .github/workflows/post-merge-package-for-build.yml
Update secret names
To fix the dev and build deployments
- [IPS-477](https://govukverify.atlassian.net/browse/IPS-477)
[IPS-477]: https://govukverify.atlassian.net/browse/IPS-477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-477 fix workflow secrets

.github/workflows/post-merge-package-for-build.yml
Update github secrets for build
actions were using incorrect secrets
- [IPS-477](https://govukverify.atlassian.net/browse/IPS-477)
[IPS-477]: https://govukverify.atlassian.net/browse/IPS-477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-477 fraud workflow secrets

acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/FraudAPIPage.java, acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/FraudPageObject.java, acceptance-tests/src/test/java/gov/di_ipv_fraud/step_definitions/FraudStepDefs.java, acceptance-tests/src/test/resources/features/FraudCRI.feature, build.gradle, infrastructure/lambda/template.yaml
Enabling JTI token field to appear in VC, and adding this check to acceptance checks.
To align with other CRIs and enable use of JTI for unique referencing.
- [LIME-569](https://govukverify.atlassian.net/browse/LIME-569)
[LIME-569]: https://govukverify.atlassian.net/browse/LIME-569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-569 adding JTI field to VC

infrastructure/lambda/template.yaml
Feature toggle of V2 to true for production test
=> LIME-921 - Feature toggle of V2 to true for production test

acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/ProveYourIdentityFullJourneyPageObject.java, infrastructure/lambda/template.yaml
Added feature toggle for int environment and fixed failing test
Experian now appears to be working with old DoB values
=> LIME-1028: Fixing failing tests and enabling crosscore v2 in integration

lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGateway.java
Increase response timeout on authenticate calls
=> Hotfix - Increase response timeout on authenticate calls

lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGateway.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyPepGateway.java, lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGatewayTest.java, lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyPepGatewayTest.java
Hotfix - Also capture latency of timed out http requests
=> Hotfix - Also capture latency of timed out http requests

infrastructure/lambda/template.yaml, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGateway.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyPepGateway.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/FraudCheckConfigurationService.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationService.java, lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/ServiceFactory.java, lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGatewayComponentTest.java, lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGatewayTest.java, lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyPepGatewayTest.java, lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/FraudCheckConfigurationServiceTest.java, lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationServiceTest.java, lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/ServiceFactoryTest.java
Removing unused CrosscoreV1 code/Tests
Add feature toggle to control keystore use.
[LIME-952](https://govukverify.atlassian.net/browse/LIME-952)
[LIME-952]: https://govukverify.atlassian.net/browse/LIME-952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-952 - Removing unused CrosscoreV1 code

lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/fraud/api/pact/IssueCredentialHandlerTest.java
Added ability to specify pact version.
To ensure we are pointed at the correct version in future and avoid failing to find pact.
- [LIME-989](https://govukverify.atlassian.net/browse/LIME-989)
[LIME-989]: https://govukverify.atlassian.net/browse/LIME-989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-989 adding consumer version for pact testing

infrastructure/lambda/template.yaml
- Added alarms that trigger when any lambda comes close to concurrent execution thresholds
- Updated bad token alarm to only fire when 5 bad tokens have been received within a minute time period
=> LIME-1007 - Adding alarms for concurrent execution thresholds

acceptance-tests/src/test/resources/features/FraudCRIAPI.feature, acceptance-tests/src/test/resources/features/english/FraudCRI.feature
Added the tag @stub to all the tests that have the @build-fraud tag against them.  Also added the tag @uat to all the tests that have @staging-fraud against them.
- [LIME-XXXX](https://govukverify.atlassian.net/browse/LIME-XXX)
=> LIME-966 Fraud: Update test tags so we are swapping build and staging

.github/workflows/dailySmokeTest.yml
Changes made to exclude dependabot from daily smoke test pages step.
To allow the build to pass successfully for Dependabot. 
- [LIME-842](https://govukverify.atlassian.net/browse/LIME-842)
[LIME-842]: https://govukverify.atlassian.net/browse/LIME-842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-842 changes to daily smoke test

acceptance-tests/src/test/resources/features/FraudCRIAPI.feature
Some API test tags have been commented out.
Currently causing consistent failures in github pipelines, plan is to bring these back in a separate workflow.
- [LIME-842](https://govukverify.atlassian.net/browse/LIME-842)
[LIME-842]: https://govukverify.atlassian.net/browse/LIME-842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-842 commenting out some test tags

infrastructure/lambda/template.yaml
Unused Parameters have been removed from template.yaml.
To tidy up the parameter store, clear out duplicated/unused parameters.
- [LIME-1118](https://govukverify.atlassian.net/browse/LIME-1118)
[LIME-1118]: https://govukverify.atlassian.net/browse/LIME-1118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1118 removing unused parameters

deploy.sh, infrastructure/lambda/private-api.yaml, infrastructure/lambda/template.yaml
The private api yaml, template yaml and deploy script have been edited.
In order to pass through the values that we receive from common-lambdas in order to support cloud front and send the messages to the correct audit event queue for TXMA.
- [LIME-1115](https://govukverify.atlassian.net/browse/LIME-1115)
[LIME-1115]: https://govukverify.atlassian.net/browse/LIME-1115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1115 template changes to support cloudfront

.github/workflows/post-merge-sonar-scan.yml
jacoco-report-aggregation needs jacoco
To correct coverage report in sonar
- [LIME-1166](https://govukverify.atlassian.net/browse/LIME-1166)
[LIME-1166]: https://govukverify.atlassian.net/browse/LIME-1166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1166 Ensure the jacoco reports from the sub projects are ran

.github/workflows/pre-merge-checks.yml, .pre-commit-config.yaml, .secrets.baseline, README.md
- Added pre-commit GHA workflow
-  Added pre-commit-config with `detect-secrets`
- Added secrets.baseline with `detect-secrets scan --slim > .secrets.baseline`
- As per ticket requirements
- [IPS-484](https://govukverify.atlassian.net/browse/IPS-484)
[IPS-484]: https://govukverify.atlassian.net/browse/IPS-484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-487: Add pre-commit GHA workflow and update pre-commit-config

.github/workflows/run-sonar-scan.yml, .github/workflows/run-unit-tests.yml, acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/FraudAPIPage.java, build.gradle, infrastructure/lambda/template.yaml, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/VerifiableCredentialService.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/fraud/api/handler/IssueCredentialHandlerTest.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/fraud/api/pact/IssueCredentialHandlerTest.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/fraud/api/pact/utils/PreLambdaHandler.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/VerifiableCredentialServiceTest.java
Updated verifiableCredentialService to use updated jwtSigning implementation and include kid in jwt headers
=> LIME-1201 - Including Opaque KID in JWT headers for VCs

acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/FraudAPIPage.java
Updated to include assertion around the vcHeader values returned (kid, typ, alg) on the response headers from the credential/issue endpoint
Updated the pre-merge API tests to include assertion around the vcHeader values returned (kid, typ, alg) on the response headers from the credential/issue endpoint
To ensure that the correct header values are always validated against when calling the credential/issue endpoint
- [LIME-1201](https://govukverify.atlassian.net/browse/LIME-1201)
[LIME-1245]: https://govukverify.atlassian.net/browse/LIME-1245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1201]: https://govukverify.atlassian.net/browse/LIME-1201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1245 - Updated pre-merge API tests

.github/workflows/post-merge-deploy-to-dev.yml, .github/workflows/post-merge-package-for-build.yml, .pre-commit-config.yaml
- Add linting step
- Code quality control
- [IPS-1132](https://govukverify.atlassian.net/browse/IPS-1132)
[IPS-1132]: https://govukverify.atlassian.net/browse/IPS-1132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-1132: Add linting
