govuk-one-login/ipv-cri-fraud-api

- deploy/template.yaml
Added conditional code signing and permissions boundary to the template.
Both the code signing and permissions boundary is required for deployments to build and downstream
- [KBV-362](https://govukverify.atlassian.net/browse/KBV-362)
None
> [KBV-362] conditional global permissions boundary and code signing

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationRequestMapper.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/request/Payload.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationRequestMapperTest.java
Added missing field mappings for thirdparty mapper and additional tests
Included source and sub building name in the mappings
Aligning with the mapping structure noted here https://govukverify.atlassian.net/wiki/spaces/PYI/pages/3157852167/Experian+Integration 
- [KBV-498](https://govukverify.atlassian.net/browse/KBV-498)
> KBV-498: Tidied up mappings and added additional tests

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationResponseMapper.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGateway.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/response/DecisionElement.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/response/OrchestrationDecision.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/response/OverallResponse.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/response/WarningsErrors.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationInfoResponseValidator.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/util/JsonValidationUtility.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationResponseMapperTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationInfoResponseValidatorTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/util/TestDataCreator.java
S1 & S2 - Prior to response validation the request status code is inspected with OK being forwarded.
S3 & S4 - After an OK status, info responses are validated, with any validation errors collected.
Info Response -
After receiving an INFO response the data is validated with IdentityVerificationInfoResponseValidator.
Validator includes a matching set of unit tests.
Removed all null checks post validation as the validator now includes this.
Rules field validation is not strict, this could be improved with informing the validator which services rules are expected from.
Post validation processing will inspect all decision elements present for rules.
The absence of a rules node will fail validation, but presence of an empty one will not.
To match scenarios requested in [KBV-499]
- …
> KBV-499 Receive and validate Experian response.

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/ContraIndicatorRemoteMapper.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationInfoResponseValidator.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationService.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationInfoResponseValidatorTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/util/JsonValidationUtilityTest.java
Fix logging mapped fraud codes as unmapped.
UnitTest coverage added to JsonValidationUtility.
Coverage Improved in IdentityVerificationInfoResponseValidator.
Fix a null pointer in IdentityVerificationService when fraud check fails due to an error response type.
Unmapped Fraud Codes where being logged with all log codes, only unmapped codes are now error logged.
JsonValidationUtility - These methods where develop as internal to the IdentityVerificationInfoResponseValidator but have been split out to be reused. The intended standalone functioning is now tested in these unit test.
IdentityVerificationInfoResponseValidator, code paths not covered by unit test are now covered.
[KBV-499](https://govukverify.atlassian.net/browse/KBV-499)
> KBV-499 Improve Unit Test Coverage and Fix logging mapped fraud codes as unmapped.

- infrastructure/lambda/template.yaml
A merged `cri-lib` PR allows us to send the CRI issuer uri to TxMA, see https://github.com/alphagov/di-ipv-cri-lib/pull/29
This PR adds a policy to allow a read of the issuer from an existing SSM param. The policy is required by lambdas using the `AuditService` to send events to TxMA.
- [KBV-567](https://govukverify.atlassian.net/browse/KBV-567)
> KBV-567 Policy to read the verifiable-credential/issuer SSM param

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationResponseMapper.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGateway.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationService.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationResponseMapperTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGatewayTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationInfoResponseValidatorTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/util/TestDataCreator.java
Additional Unit test coverage added to ThirdPartyFraudGateway and IdentityVerificationService targeting the error pathways.
IdentityVerificationResponseMapper -
Reordered the switch statements so standard path is first, then error, then failure.
Naming in mapErrorResponse changed so that it is clear that error code or error message, used to generate the fraud check error message, will if not found be filled in with a default value.
UnitTests added for Error, Warn and Warning response types.
UnitTest added for code handling when error code, and error message is not provided.
ThirdPartyFraudGateway -
Changed error messages to be generated from final static strings so they can be used in unit testing.
Unit tests added for 300, 400, 500, and unhandled http status code paths, matching the …
> KBV-590 - Improve unit test coverage in error pathways.

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationService.java
THIRD_PARTY_REQUEST_ENDED events now have ThirdPartyFraudCodes attached.
Contra Indicators where being sent incorrectly in place of ThirdPartyFraudCodes.
- [KBV-587](https://govukverify.atlassian.net/browse/KBV-587)
> KBV-587 Attach ThirdPartyFraudCodes to THIRD_PARTY_REQUEST_ENDED event.

- infrastructure/lambda/template.yaml
Added splunk logging subscription filters to apis and all lambdas
So that splunk logs can be read in production for the fraud CRI
- [KBV-569](https://govukverify.atlassian.net/browse/KBV-569)
> KBV-569: Added splunk logging subscription filters to apis and all lambdas

- infrastructure/lambda/template.yaml
Adding provisioned concurrency in prod
To align with other CRIs and improve performance
- [KBV-561](https://govukverify.atlassian.net/browse/KBV-561)
> KBV-561: Adding provisioned concurrency for fraud in prod

- infrastructure/lambda/template.yaml
Updating VC exp to 2 hours across environments
To align with other CRIs and session times
- [KBV-620](https://govukverify.atlassian.net/browse/KBV-620)
> KBV-620: Updating MaxJwtTtl in the higher envs to 2 hours

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGateway.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/ServiceFactory.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/util/SleepHelper.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGatewayTest.java
HTTP requests will be retried when they return the following status codes or the HTTP connection attempt times out.
429 - Too many recent requests.
500-599 - All Server Errors.
The retry logic uses exponential back off, retrying up to 7 times after the initial request.
This has a potential of adding up to 30 seconds of delay if no subsequent retries return a 200 - OK response.
In the case of 7 retries each with HTTP connection timeouts, this could have been an additional 30 seconds per request.
As such connection timeout has been reduced from 30 to 10 seconds, before checking if it should retry again.
There were no attempts to retry requests to the ThirdParty if potentially recoverable http responses are returned or http connection timeouts occurred.
- …
> KBV-592: Add Request retries to ThirdPartyFraudGateway

- infrastructure/lambda/template.yaml
Removed ContraIndicationTableName parameter and associated DynamoDB table.
Removed creation off APIKey1 and APIKey2.
DynamoDB is no longer used for contra indicator mapping.
APIKey1/APIKey2 have been replaced with core-infrastructure-ApiKey1/core-infrastructure-ApiKey2.
- [KBV-629](https://govukverify.atlassian.net/browse/KBV-629)
> KBV-629 Remove unused sections of template.

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/handler/FraudHandler.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/ServiceFactory.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/fraud/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/VerifiableCredentialService.java
Updated Fraud CRI submodule to track changes in common-lib and common-lambdas. 
Adjusted usage of the Audit Service to match.
VerifiableCredentialService changed to use a configurationService via constructor parameter.
Moved the creation of several services in FraudHandler into the ServiceFactory.
The Audit Service used for sending TXMA events had been updated but Fraud API was tracking the older version.
Creation of the configuration service was duplicated in several places within IssueCredential.
Adding constructor parameter enables one configuration service reuse though-out.
FraudHandler constructor was creating duplicate objects and services, using the centralised service factory avoids this.
- [KBV-681](https://govukverify.atlassian.net/browse/KBV-681)
> KBV-681 Track AuditService changes in common-lib/common-lambdas.

- infrastructure/lambda/public-api.yaml
- infrastructure/lambda/template.yaml
Don't use API keys in the dev environment.
Moved AccessToken components section out of public-api.yaml back in to the public api section of template.yaml.
A header api key is now required only in the non dev environments.
API Key
This avoids the issue where dev stacks fail to deploy due to too many stacks sharing the API Keys, giving the error 
- The Usage Plan limit for  API Key core-ixxxxxxxx has been reached.
AccessToken
The public api AccessToken required an API key to be provided in the header. 
The section that controls this was being included from public-api.yaml preventing using conditional statements and variables.
- [KBV-649](https://govukverify.atlassian.net/browse/KBV-649)
> KBV-649 Do not use usage plans for API Keys when the environment is dev.

- infrastructure/lambda/template.yaml
Other teams seem to be stabilising on 2048Mb for memory size.
On Lambda, CPU scales with memory, so more memory means more CPU as well.
See alphagov/di-ipv-cri-address-api#163
and alphagov/di-ipv-cri-kbv-api#144
and alphagov/di-ipv-core-back#300
and alphagov/di-ipv-spot/pull/307
from 512Mb to 2048Mb
> Bump memory to 2Gb

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/PersonIdentityValidator.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationRequestMapperTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/util/TestDataCreator.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/VerifiableCredentialServiceTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/fraud/api/util/TestDataCreator.java
Added unit test to prove that an IdentityVerificationRequest can be created with two or more addresses.
Updated the SignedVerifiableCredentialJWT unit test to prove that a signed JWT VC can be created with two or more addresses.
Added a check to the PersonIdentityValidator to fail users with 0 addresses.
Readability improvements in IdentityVerificationRequestMapperTest.
It was unknown if FraudCRI-API could handle multiple address.
As no test user currently has two addresses, a VC for a user with two address was generated using an adhoc solution with evidence attached in KBV-520.
Users with 0 addresses would fail the fraud check, this fails the user for this error condition earlier.
IdentityVerificationRequestMapperTest had excessive duplication of object paths.
- …
> KBV-520 Send multiple addresses to Experian

- infrastructure/lambda/template.yaml
Changed architecture to arm64 and set memory values to align with other CRIs for each environment.
Testing for other CRI's and now shown for Fraud CRI demonstrated a small improvement in cold starts using arm64 architecture and a much larger improvement for cold starts with increased memory settings.
- [KBV-767](https://govukverify.atlassian.net/browse/KBV-767)
> KBV-767 Improve performance of Fraud API CRI

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/handler/FraudHandler.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationService.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/handler/CredentialHandlerTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationServiceTest.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/fraud/api/handler/IssueCredentialHandler.java
AuditEvents are sent using an AuditEventContext.
FraudAPI was updated to use the latest AuditService changes, but message sending was not updated to include an AuditEventContext. This meant although events where successfully sent they where now in the wrong format.
- [KBV-813](https://govukverify.atlassian.net/browse/KBV-813)
> KBV-813 Use AuditEventContext when sending AuditEvent's.

- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/fraud/api/handler/IssueCredentialHandlerTest.java
Track usage of AuditService in IssueCredentialHandler.
Calling pattern needed updating to match.
- [KBV-813](https://govukverify.atlassian.net/browse/KBV-813)
> KBV-813 Track AuditService changes in IssueCredentialHandler.

- .github/workflows/post-merge-package-for-build.yml
Update to push test image to staging
To unblock the deployment pipeline
> LIME-25: Updating build to use acceptance repo rather than home

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/PersonIdentityValidator.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/util/JsonValidationUtility.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationRequestMapperTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationInfoResponseValidatorTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/PersonIdentityValidatorTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/util/JsonValidationUtilityTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/util/TestDataCreator.java
PersonIdentityValidator has been updated to check addresses are valid.
Validation Errors will be logged for -
- There not being an address that evaluates as a CURRENT AddressType.
- There being only PREVIOUS AddressTypes.
- There being no valid addressTypes.
- Any address AddressType is evaluated as null.
- Address counts 0 or >32
Range validation message changed to a string format and the range checked included.
Logging added for number of address and types.
PersonIdentityValidator
Address information was not checked prior to conversion into the Experian request format. Addresses are not required to be in-order, with an artificial limit of 32.
A addressTypes are counted, with 1 CURRENT address required to pass validation. The absence of CURRENT address or presence of null addressType …
> KBV-771 Validate address information prior to fraud check.

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationResponseMapper.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGateway.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/request/PEPRequest.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/response/PEPResponse.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/ConfigurationService.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationInfoResponseValidator.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationService.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/ServiceFactory.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGatewayTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationServiceTest.java
- Added "pepEnabled" flag to configuration service to be used in turning PEP check on and off
- Updated ThirdPartyFraudGateway to have an additional request for PEPcheck should the pepEnabled flag be true
- Added PEPRequest and PEPResponse classes (Same as IdentityVerificationRequest/Response for now) Which will need to be reviewed in LIME-37
To implament the PEP request into our flow
> LIME-11 - Implementing PEP request

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityScoreCalculator.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationInfoResponseValidator.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationService.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/ServiceFactory.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationInfoResponseValidatorTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationServiceTest.java
Updated Identity score Calculator to give a score of 2 if pep check and fraud check are successful
To allow for a score of 2 for users who have completed a pep check
> Lime 43 - Updating IdentityScoreCalculator

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationInfoResponseValidator.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationInfoResponseValidatorTest.java
Changed Max value for score in the IdentityVerificationInfoResponseValidator.java
To allow for the updated fraud score range in fraud check caused by the addition of pep Check
> LIME-37 - Updating max fraud score value in validator

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationService.java
Removed the PEP ID from the VC
There is a change to follow that will include both transactionIDs in the VC
> LIME-34: Removed the pep transactionId from the VC until we update the VC

- .github/workflows/post-merge-deploy-to-dev.yml
- .github/workflows/post-merge-package-for-build.yml
- .github/workflows/pre-merge-integration-test.yml
- Add config to git checkout to include submodules
- To correct a github actions execution failure
- [OJ-988](https://govukverify.atlassian.net/browse/OJ-988)
> OJ-988 - Reinstate GHA submodules checkout

- infrastructure/lambda/template.yaml
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/ConfigurationService.java
- Added `ssm:GetParameter` permission for the pepEnabled param
- pepEnabled was previously incorrectly defaulting to `false`
- [OJ-988](https://govukverify.atlassian.net/browse/OJ-988)
> OJ-988 - Add ssm:GetParameter permission for pepEnabled

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationRequestMapper.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationRequestMapperTest.java
PEP check changed to use only the current address in requests.
Third-party API does not support multiple addresses for PEP checks.
- [LIME-234](https://govukverify.atlassian.net/browse/LIME-234)
> LIME-234 Use only the current address in pep requests

- infrastructure/lambda/template.yaml
Removed old prod log subscription
Because the old endpoint is being decommissioned
> Removing-CSLS-Rust: Removing old log subscriptions

- infrastructure/lambda/template.yaml
Updated description of public and private apis
To trigger apis to redeploy in fraud environments so the renaming appears in cloud watch
> LIME-191: Updating description of APIs to trigger redeploy

- infrastructure/lambda/template.yaml
Added alerting for fraud CRI
for 400s, 500s and Lambda errors
To enable us to actively monitor the fraud CRI
> LIME-191: Added basic error alerting for the fraud CRI

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationResponseMapper.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGateway.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/handler/FraudHandler.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationService.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/ServiceFactory.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationResponseMapperTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGatewayTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/handler/CredentialHandlerTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationServiceTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/ServiceFactoryTest.java
- lambdas/issuecredential/build.gradle
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/fraud/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/fraud/api/handler/IssueCredentialHandlerTest.java
- lib/build.gradle
- lib/src/main/java/uk/gov/di/ipv/cri/fraud/library/metrics/Definitions.java
- settings.gradle
Added metrics to FraudCRI FraudCheck Lambda
Identity Check - Completed ok/error
Issue Credential - Completed ok/error
PersonIdentityValidator - pass/fail
Fraud Check Request - succeeded/failed
PEP Check Request - succeeded/failed
OverallScore - 0/1/2
Fraud response Contra Indicators - generated
PEP response Contra Indicators - generated
HTTP Connection Send - request_created/send_ok/send_retry/send_fail
Third Party Response Type Fraud - info/error/unknown
Third Party Response Type PEP - info/error/unknown
IdentityVerificationInfoResponseValidator Fraud - pass/fail
IdentityVerificationInfoResponseValidator PEP - pass/fail
Kept the two existing metrics in place until alarms and panels are converted over.
Added internal lib for fraudCRI
Corrected unit tests in …
> LIME-189 Capture FraudCRI Metrics

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/domain/IdentityVerificationResult.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/handler/FraudHandler.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/persistence/item/FraudResultItem.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationService.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/handler/CredentialHandlerTest.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/fraud/api/domain/audit/Evidence.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/fraud/api/persistence/item/FraudResultItem.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/fraud/api/util/IssueCredentialFraudAuditExtensionUtil.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/fraud/api/handler/IssueCredentialHandlerTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/VerifiableCredentialServiceTest.java
Updated fraud to:
Capture the decisionScore from Experian
Save the decisionScore
Record the decision score in the VC
So we can track users with 0 decision score and where they originate from
- [LIME-253](https://govukverify.atlassian.net/browse/LIME-253)
> LIME-253: Adding decision score from the fraud check to the TxMA cred issued event

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/ConfigurationService.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityScoreCalculator.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationService.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/ServiceFactory.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/ConfigurationServiceTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityScoreCalculatorTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationServiceTest.java
Fraud score calculator updated.
Two new parameters added for no file found with third party threshold and ucodes that if received do not allow the score beyond 0.
Changed following a review of the fraud process with Experian and what should happen if the user cannot be found within the thirdparty records
- [LIME-248](https://govukverify.atlassian.net/browse/LIME-248)
> LIME-248: Updated score calculator

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGateway.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGatewayTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/fraud/library/metrics/Definitions.java
Capture metrics at the final state after a request has been sent in ThirdPartyFraudGateway.
Add missing THIRD_PARTY_REQUEST_CREATED metric in fraudCheck request.
To capture metrics for reaching max retries or unexpected status codes responses.
Moved THIRD_PARTY_REQUEST_SEND_OK to be determined at method exit rather than mid try.
Added verification of event probe metrics to unit tests.
- [LIME-189 ](https://govukverify.atlassian.net/browse/LIME-189 )
> LIME-189 Adjust ThirdPartyFraudGateway metrics

- build.gradle
- lambdas/fraudcheck/build.gradle
- lambdas/issuecredential/build.gradle
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/fraud/api/handler/IssueCredentialHandler.java
(Merge after https://github.com/alphagov/di-ipv-cri-lib/pull/106)
Send CRI_END audit event when VC is being returned.
Add kms to issuecredential dependancies.
Update CRI lib version to 1.3.1
CRI_END audit event added per LIME-173.
Adding kms dependancy to issuecredential due to auto resolution failing with a locally generated cri lib. This aligns issuecredential build with the fraudcheck lambda build which had no issue due to already having the dependancy present.
CRI lib 1.3.1 contains the change needed.
- [LIME-173](https://govukverify.atlassian.net/browse/LIME-173)
> LIME-173 send IPV_FRAUD_CRI_END audit event.

- infrastructure/lambda/template.yaml
- MaxJwtTtlMapping increased from 2 hours to 6 months.
- [LIME-243](https://govukverify.atlassian.net/browse/LIME-243)
> LIME-243 - Extend VC Validity to 6 months for production environment

- .github/workflows/build-image.yml
- acceptance-tests/run-tests.sh
Updated run-tests.sh to work with ssm param stack
and
Assumed permissions so that image can be tested before being pushed
To allow image to be constructed and pushed for pipeline and to ensure image is properly tested
> LIME-117: Updated run-tests and build image to assume aws credentials

- build.gradle
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationService.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/util/FraudAuditGeneratorTest.java
Note: This PR will need to be merged after https://github.com/alphagov/di-ipv-cri-lib/pull/148
Replaced THIRD_PARTY_REQUEST_ENDED with RESPONSE_RECEIVED
> LIME-406 - Replaced THIRD_PARTY_REQUEST_ENDED with RESPONSE_RECEIVED

- acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/FraudPageObject.java
- acceptance-tests/src/test/java/gov/di_ipv_fraud/step_definitions/FraudStepDefs.java
- acceptance-tests/src/test/resources/features/FraudCRI.feature
Create checkDetails and failedcheckDetails component in the Fraud CRI VC
checkDetails | Array | Array of objects for checks that succeeded (partially or completely).
-- | -- | --
failedcheckDetails | Array | JSON array for checks that completely failed.
[LIME-257]
Lime-257-checkDetails and failedCheckDetails test added to FraudCRI.feature
- [LIME-257](https://govukverify.atlassian.net/browse/LIME-257)
1. Crosscore Authenticate and PEP completed and user not PEP
2. Crosscore Authenticate and PEP completed and user is a PEP
3. Mortality u-code returned
4. Crosscore Authenticate completed and PEP not completed due to error from Experian
5. Crosscore Authenticate completed and PEP not completed due to technical failure
6. Decision score below 35
[LIME-257]: …
> Lime-257-checkDetails and failedCheckDetails test added to FraudCRI.feature

- infrastructure/lambda/template.yaml
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationService.java
Added logging & alerting into Fraud CRI for spike in fraud scores.
- [LIME-333](https://govukverify.atlassian.net/browse/LIME-333)
[LIME-333]: https://govukverify.atlassian.net/browse/LIME-333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-333 - Add logging & alerting into Fraud CRI for spike in fraud scores

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGateway.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGatewayTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/fraud/library/metrics/Definitions.java
- Fraud Check duration metric added to AWS Cloudwatch.
- PEP Check duration metric added to AWS Cloudwatch.
- [LIME-419](https://govukverify.atlassian.net/browse/LIME-419)
[LIME-419]: https://govukverify.atlassian.net/browse/LIME-419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-419 - Third Party response times recorded in metrics

- .github/workflows/pre-merge-integration-test.yml
- acceptance-tests/src/test/java/gov/di_ipv_fraud/service/ConfigurationService.java
- acceptance-tests/src/test/resources/features/FraudCRIAPI.feature
Updating pre-merge-integration workflow and tests to use shared-dev
To fix pre-merge-integration test github action
> LIME-466 - Updating tests to use shared-dev

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/domain/IdentityVerificationResult.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/domain/audit/ExperianCrossCoreResponse.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/domain/audit/TPREFraudAuditExtension.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationService.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/handler/CredentialHandlerTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationServiceTest.java
Replaced CIs with thirdPartyFraudCodes in THIRD_PARTY_REQUEST_RECEIVED audit event
> LIME-473 - Replacing CIs with thirdPartyFraudCodes in auditEvents

- .github/workflows/dailySmokeTest.yml
- .github/workflows/gradleBuildTest.yml
- .github/workflows/pre-merge-integration-test.yml
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationResponseMapper.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/response/AuthConsumer.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/response/AuthPlusResults.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/response/AuthResults.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/response/DecisionElement.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/response/IDandLocDataAtCL.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/response/LocDataOnlyAtCLoc.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/response/OtherData.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/util/TestDataCreator.java
Added logging of Activity History score related fields found in third party responses for use in Activity history score calculation.
To determine what we get sent back in the fields so that we can appropriately calculate activity history score
> LIME-468 - Activity History score logging

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/response/OtherData.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGatewayComponentTest.java
Removed unused response object with incorrect data type
To fix error where PEP responses were not being mapped now we are accepting the entire response not just the decision related sections
> LIME-468: Removed unused response object with wrong data type

- .github/workflows/pre-merge-integration-test.yml
- acceptance-tests/run-local-tests.sh
- acceptance-tests/src/test/java/gov/di_ipv_fraud/model/AuthorisationResponse.java
- acceptance-tests/src/test/java/gov/di_ipv_fraud/model/AuthorizationCode.java
- acceptance-tests/src/test/java/gov/di_ipv_fraud/model/State.java
- acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/FraudAPIPage.java
- acceptance-tests/src/test/java/gov/di_ipv_fraud/service/ConfigurationService.java
- acceptance-tests/src/test/java/gov/di_ipv_fraud/step_definitions/FraudAPIStepDefs.java
- acceptance-tests/src/test/resources/features/FraudCRI.feature
- acceptance-tests/src/test/resources/features/FraudCRIAPI.feature
Adding API tests to cover a happy path journey’s for Fraud CRI
This consists of the changes made as part of https://govukverify.atlassian.net/browse/LIME-415
API tests have been added to cover the following Fraud CRI journey
Fraud check + Peps complete (AC1)
Decision score below 35 (AC2)
User found of mortality register (AC3)
Users address possibly belongs to someone else / Home telephone supplied does not match database / Potential developed identity (AC5)
Have also updated the tags on the tests.
> LIME-415 Fraud CRI API tests

- acceptance-tests/src/test/java/gov/di_ipv_fraud/utilities/Driver.java
Added argument to chromeDriver to allow remote origins (eg localhost)
To fix aws pipeline testing stage
> LIME-468 - Fixing aws pipeline testing stage

- build.gradle
- infrastructure/lambda/template.yaml
Enabled vc-expiry-removed feature toggle in Fraud CRI and disabled it in dev environment
Release flag can't be enable on cri-dev stacks as they will be cross wired or blocked from deploying.
This is due to "/release-flags/vc-expiry-removed" path being forced by cri-lib as absolute rather than relative per stack.
On cri-dev, an unused variable is set instead with the feature toggle falling back to false by default.
> LIME-567 - Removed expiry on VC

- acceptance-tests/run-local-tests.sh
- acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/FraudPageObject.java
- acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/Headers.java
- acceptance-tests/src/test/java/gov/di_ipv_fraud/service/ConfigurationService.java
- acceptance-tests/src/test/java/gov/di_ipv_fraud/step_definitions/FraudStepDefs.java
- acceptance-tests/src/test/java/gov/di_ipv_fraud/step_definitions/ProveYourIdentityFullJourneyStepDefs.java
- acceptance-tests/src/test/resources/features/FraudCRI.feature
- acceptance-tests/src/test/resources/features/ProveYourIdentityFullJourneyRoute.feature
This pr aligns tests with page title fixes in common-express.
Fixes some tests not finding the full page title, with service name and gov.uk appended.
Corrects test that are looking for and replicating a hardcoded page title
Service name and gov.uk are dynamically included in the page title check to avoid replicating the string in every test.
Correct issues causing end to end test to fail.
Aligned run local with dl-api, and passport-api-v1
[fraud-front](https://github.com/alphagov/di-ipv-cri-fraud-front/pull/348 ) is being updated to use common-express to v1.0.0
Several tests where looking for hardcoded page title text and failing to match, the title is now generated separately and checked, rather than duplicated though the test as a string.
While testing the title page matching, the …
> LIME-633 Update acceptance tests to look for the full page title

- acceptance-tests/build.gradle
- acceptance-tests/src/test/java/gov/di_ipv_fraud/model/Check.java
- acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/FraudAPIPage.java
- acceptance-tests/src/test/java/gov/di_ipv_fraud/step_definitions/FraudAPIStepDefs.java
- acceptance-tests/src/test/resources/features/FraudCRIAPI.feature
- infrastructure/lambda/template.yaml
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/domain/IdentityVerificationResult.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/handler/FraudHandler.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationService.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/handler/CredentialHandlerTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationServiceTest.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/fraud/api/domain/Evidence.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/fraud/api/domain/checkdetails/Check.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/fraud/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/ConfigurationService.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/VerifiableCredentialService.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/fraud/api/util/EvidenceHelper.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/fraud/api/util/IssueCredentialFraudAuditExtensionUtil.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/fraud/api/handler/IssueCredentialHandlerTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/VerifiableCredentialServiceTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/fraud/api/util/EvidenceHelperTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/fraud/api/util/IssueCredentialAuditGeneratorTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/fraud/library/persistence/item/FraudResultItem.java
Added activity history score to the VC
Added empty check to the VC for activity from
```
{
"checkMethod": "data",
"activityFrom": "2019-01-01",
"identityCheckPolicy": "none"
}
```
Updated tests
Added new acceptance tests
So that we could return activity history score while still adhering to RFC 24
> LIME-565: Adding activity history score and associated checks to the VC

- infrastructure/lambda/template.yaml
Enabled activity history score in integration and production
to allow us to use AC in production for F2F
> LIME-565: Toggling activity history on in integration and production

- acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/FraudPageObject.java
- acceptance-tests/src/test/java/gov/di_ipv_fraud/step_definitions/FraudStepDefs.java
- acceptance-tests/src/test/resources/features/FraudCRI.feature
Remove the existing test step where we validate the expiry date as 6 months from the current date
Add a new test step to validate that the exp date field is no longer available in the VCs in Fraud CRI
(https://govukverify.atlassian.net/browse/LIME-670)
> Lime 670 no exp date field in vc fraud cri

- infrastructure/lambda/template.yaml
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/handler/FraudHandler.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/ConfigurationService.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/ConfigurationServiceTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationServiceTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/fraud/library/persistence/item/FraudResultItem.java
Updated the ttl for result items
To ensure results expire with the session as expected
> LIME-698: Fixed issue where ttl was not set correctly for results

- infrastructure/lambda/template.yaml
Correct math in `FraudAPIGW5XXErrorsPrivatePercentage/PercentageFailure` calculation
> Correct math in FraudAPIGW5XXErrorsPrivatePercentage/PercentageFailure calculation

- README.md
- acceptance-tests/src/test/resources/features/FraudCRI.feature
- infrastructure/lambda/template.yaml
Removed 4XX alarm from template
So that we are no longer running P1 alerts for 400's in production
> LIME-862: Removing the 4XX alarm from the Fraud CRI

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/handler/FraudHandler.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/ServiceFactory.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/ServiceFactoryTest.java
Add custom SSL context to the apache http client 
Custom SSL configuration was incorrectly assumed not to be needed.
- [LIME-889](https://govukverify.atlassian.net/browse/LIME-889)
[LIME-889]: https://govukverify.atlassian.net/browse/LIME-889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-889 Add missing SSL context configuration

- infrastructure/lambda/template.yaml
Increase api rate/burst limits and lambda cpu allocation
Align FraudAPI with DLAPI values
- [LIME-727](https://govukverify.atlassian.net/browse/LIME-727)
[LIME-727]: https://govukverify.atlassian.net/browse/LIME-727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-727 Increase Fraud API Throttle/Throttling limits

- infrastructure/lambda/template.yaml
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/FraudCheckConfigurationService.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/FraudCheckConfigurationServiceTest.java
Add CrosscoreV2 feature toggle
Improve coverage in FraudCheckConfigurationService
CrosscoreV2 feature toggle to control enablement.
FraudCheckConfigurationService was missing several asserts on ssm values.
Add assert for useCrosscoreV2.
- [LIME-912](https://govukverify.atlassian.net/browse/LIME-912)
[LIME-912]: https://govukverify.atlassian.net/browse/LIME-912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-912 Add CrosscoreV2 feature toggle

- build.gradle
- lambdas/fraudcheck/build.gradle
- lambdas/issuecredential/build.gradle
Upgrade aws embedded metrics to 2.0.0 
4.0+ cannot be used with-out code changes in CRI lib.
2.0 is code compatible and includes a tcp client change that may resolve the Socket closed exception logged by software.amazon.cloudwatchlogs.emf.sinks.TCPClient and subsequent failure of metrics to be captured by that lambda instance.
- [LIME-990](https://govukverify.atlassian.net/browse/LIME-990)
[LIME-990]: https://govukverify.atlassian.net/browse/LIME-990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Lime 990 - upgrade aws embedded metrics from v1.0.6 to v2.0

- .github/workflows/pre-merge-checks.yml
- acceptance-tests/src/test/resources/features/FraudCRI.feature
- build.gradle
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGateway.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyPepGateway.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/CrosscoreV2Configuration.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/FraudCheckConfigurationService.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationInfoResponseValidator.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationService.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/ServiceFactory.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/TokenRequestService.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGatewayComponentTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGatewayTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyPepGatewayTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/handler/FraudHandlerTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/FraudCheckConfigurationServiceTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationServiceTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/ServiceFactoryTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/TokenRequestServiceTest.java
- Made updates to the ThirdPartyGateways to facilitate a call to CrosscoreV2 conditionally (based on the value of CrosscoreV2/enabled feature toggle parameter).
- Refactored FraudCheckConfigurationService parameters related to CrosscoreV2 to live inside of a new configuration class called crosscoreV2Configuration (Also refactored TokenRequestService to use this new configuration)
- Updated ServiceFactory to pass the tenantID used in IdentityVerificationRequestMapper conditionally based on V2 feature toggle parameter
- Wrote unit tests to cover new route
- Added fix to Sonar unit Test coverage calculations
> LIME-951 - Creating Call to crosscoreV2

- .github/workflows/pre-merge-checks.yml
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationResponseMapper.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/response/WarningsErrors.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationInfoResponseValidator.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationWarningsErrorsLogger.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationInfoResponseValidatorTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationWarningsErrorsLoggerTest.java
Correct warningsErrors responseType to be mapped as string instead of an enum
Added dedicated logger for warnings and errors - IdentityVerificationWarningsErrorsLogger.
"ResponseType" in warningsErrors, is indicated to be a String and have values that do not match the global enum "ResponseType".
IdentityVerificationWarningsErrorsLogger - 
- To allow the CRI to attempt to retrieve warnings/errors from all ResponseType if present, even if the response is not fully complete - to aid investigating response errors.
- To avoid changing the behaviour or adding the above unrelated functionality to the IdentityVerificationInfoResponseValidator.
- [LIME-1010](https://govukverify.atlassian.net/browse/LIME-1010)
[LIME-1010]: https://govukverify.atlassian.net/browse/LIME-1010?atlOrigin=eyJpIjoiNWRkNTlj …
> LIME-1010 Correct warningsErrors responseType to be mapped as string instead of an enum

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationInfoResponseValidator.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/PersonIdentityValidator.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/util/JsonValidationUtility.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationInfoResponseValidatorTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/util/JsonValidationUtilityTest.java
Align IdentityVerificationInfoResponseValidator with Crosscore2 response.
Correct unboxing null pointer when response DecisionElement has no score field.
Moved warnings errors handling into separate method.
Some fields previously returned as empty will now not be present.
Validation on the value range of the score, was unboxing a null Integer.
A null score will now fail the validator, as it is a required field.
warnings errors handling moved - to remove complexity code smell
- [LIME-920](https://govukverify.atlassian.net/browse/LIME-920)
[LIME-920]: https://govukverify.atlassian.net/browse/LIME-920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-920 Align IdentityVerificationInfoResponseValidator with crosscore2 response

- infrastructure/lambda/template.yaml
Release to enable crosscore V2 in production
To enable a connection test before the crosscore switchover
> LIME-921: Toggling on in production to test connections

- infrastructure/lambda/template.yaml
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/response/AccessTokenHeader.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/dto/response/AccessTokenPayload.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/CrosscoreV2Configuration.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/TokenRequestService.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/util/AccessTokenValidator.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/FraudCheckConfigurationServiceTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/TokenRequestServiceTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/fraud/library/error/ErrorResponse.java
- lib/src/main/java/uk/gov/di/ipv/cri/fraud/library/metrics/ThirdPartyAPIEndpointMetric.java
- lib/src/test/java/uk/gov/di/ipv/cri/fraud/library/metrics/ThirdPartyAPIEndpointMetricTest.java
- Added validation to accessToken JWT to verify the alg, sub and iss fields of the header/payload.
- Amended tests to reflect changes
> LIME-1012 - Adding validation to accessToken JWT

- .github/workflows/dailySmokeTest.yml
- acceptance-tests/build.gradle
- acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/FraudPageObject.java
- acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/ProveYourIdentityFullJourneyPageObject.java
- acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/UniversalSteps.java
- acceptance-tests/src/test/java/gov/di_ipv_fraud/step_definitions/FraudStepDefs.java
- acceptance-tests/src/test/java/gov/di_ipv_fraud/utilities/Driver.java
- acceptance-tests/src/test/resources/log4j2.xml
Fix smoke tests via using the wrapper vs gradle directly
- Added note to update the following cucumber_version, selenium_version and webdrivermanager_version together
- Updated cucumber_version, selenium_version and webdrivermanager_version
- Fixed race condition for page title assertions via waitForPageToLoad
- Fix setHeadless removal
- Added "with gradle-version: wrapper" to setup gradle action
- [LIME-991](https://govukverify.atlassian.net/browse/LIME-991)
[LIME-991]: https://govukverify.atlassian.net/browse/LIME-991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-991 Fix smoke tests via using the wrapper vs gradle directly

- acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/FraudPageObject.java
Attempt fix intermittent failures on the VC page by wait for the element that is being clicked to appear in ac tests.
Mitigate intermittent failures on the element click.
- [LIME-991](https://govukverify.atlassian.net/browse/LIME-991)
[LIME-991]: https://govukverify.atlassian.net/browse/LIME-991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-991 Fix race condition reading VC from dynamic element

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGateway.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyPepGateway.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGatewayTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyPepGatewayTest.java
Updated the values for Fraud and PEPs for timeouts.
To handle latency issues with Fraud.
- [LIME-1030](https://govukverify.atlassian.net/browse/LIME-1030)
[LIME-1030]: https://govukverify.atlassian.net/browse/LIME-1030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1030 Editing Fraud and Pep timeout values

- infrastructure/lambda/template.yaml
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/FraudCheckConfigurationService.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/ServiceFactory.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/FraudCheckConfigurationServiceTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/ServiceFactoryTest.java
No longer add the cc1 keystore to the http client -
- note ssl context is still used and "TLSv1.2" requested.
Remove permissions for the environment CC1 parameters and secrets.
Part of the clean up of remaining CC1 parameters and secrets.
- [LIME-952](https://govukverify.atlassian.net/browse/LIME-952)
[LIME-952]: https://govukverify.atlassian.net/browse/LIME-952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-952 Remove CC1 Keystore

- acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/FraudPageObject.java
Update the 302 error message assert to match the oauth error message now set by the API
Previously this was not set and relied on a fall back default in common-express.
- [LIME-1045](https://govukverify.atlassian.net/browse/LIME-1045)
[LIME-1045]: https://govukverify.atlassian.net/browse/LIME-1045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1045 (AC Test) Update the 302 error message assert to match the oauth error message now set by the API

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGateway.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyPepGateway.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/TokenRequestService.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGatewayComponentTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGatewayTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyPepGatewayTest.java
Added logging of ClientReferenceId to API requests
Changed logging of Correlation Id in token request to CorrelationId
To enable tracing errors to specific requests CRI side and remotely with the third party.
- [LIME-1070](https://govukverify.atlassian.net/browse/LIME-1070)
[LIME-1070]: https://govukverify.atlassian.net/browse/LIME-1070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1070 Log ClientReferenceId/CorrelationId of all api requests

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/TokenRequestService.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/TokenRequestServiceTest.java
Token request service now saves a token in dynamo based on the test strategy routing. Making it possible to have 1 token generated for and used by our 3rd party stubs and another for UAT/LIVE.
This change was made as tokens are cached and re-used for up to 30 mins for third party requests. The logic in this PR negates the possibility of a token being generated by our stub, stored in dynamo, and then re-used in a later request intended for our 3rd parties UAT environment.
> LIME-967 - Updating TokenSaves to save a token based on TestStrategy

- acceptance-tests/src/test/java/gov/di_ipv_fraud/utilities/BrowserUtils.java
The value of "lang" has been edited to "lng" in acceptance-tests.
The value has been changed in common-express. As our front end was changed for the language toggle, this change is required for our api tests to be aligned for this value.
- [LIME-1069](https://govukverify.atlassian.net/browse/LIME-1069)
> LIME-1069 aligning lng cookie value in tests

- acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/FraudPageObject.java
Reduce sensitivity of ac tests to test runner cpu load
Timing inside the ac test is not tolerant of any delays due to load on the system the runners are executing, introducing intermittent test failures.
- [LIME-1075](https://govukverify.atlassian.net/browse/LIME-1075)
[LIME-1075]: https://govukverify.atlassian.net/browse/LIME-1075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1075 Reduce sensitivity of ac tests to test runner cpu load

- acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/FraudPageObject.java
- acceptance-tests/src/test/java/gov/di_ipv_fraud/step_definitions/FraudStepDefs.java
- acceptance-tests/src/test/resources/features/english/FraudCRI.feature
Added language toggle test
To add coverage for a new shared component called [one login language toggle](https://www.npmjs.com/package/@govuk-one-login/one-login-language-toggle) 
- [LIME-1069](https://govukverify.atlassian.net/browse/LIME-1069)
[LIME-1069]: https://govukverify.atlassian.net/browse/LIME-1069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1069 - Added language Toggle Test

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/domain/IdentityVerificationResult.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/domain/check/FraudCheckResult.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationResponseMapper.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationService.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationResponseMapperTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/handler/FraudHandlerTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityScoreCalculatorTest.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/IdentityVerificationServiceTest.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/fraud/api/domain/Evidence.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/fraud/api/handler/IssueCredentialHandlerTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/fraud/api/pact/IssueCredentialHandlerTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/fraud/api/service/VerifiableCredentialServiceTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/fraud/library/persistence/item/FraudResultItem.java
Send decisionScore as Integer in VC_ISSUED audit event
Keeps previous behaviour of decisionScore not being present in VC (not requested previously)
decisionScore was being captured and sent as a String
- [LIME-1166](https://govukverify.atlassian.net/browse/LIME-1166)
[LIME-1166]: https://govukverify.atlassian.net/browse/LIME-1166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1166 Send decisionScore as Integer in VC_ISSUED audit event

- .github/workflows/post-merge-sonar-scan.yml
Post merge of LIME-1166 the sonar scan of main did not happen
Add dedicated post merge sonar action scan action - to avoid re-running the heavier pre-merge workflow post merge.
- [LIME-1166](https://govukverify.atlassian.net/browse/LIME-1166)
[LIME-1166]: https://govukverify.atlassian.net/browse/LIME-1166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1166 Correct sonar-scan not running against main post merge

- .github/workflows/post-merge-sonar-scan.yml
Remove build dependency in sonar scan workflow
Sonar scan workflow was based on existing workflow, which had a build step.
- [LIME-1166](https://govukverify.atlassian.net/browse/LIME-1166)
[LIME-1166]: https://govukverify.atlassian.net/browse/LIME-1166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1166 Remove dependency in sonar scan workflow

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyFraudGateway.java
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/ThirdPartyPepGateway.java
Increase authenticate-plus timeout to 6 seconds
Correct pool timeouts being set to unreasonably high values
HTTP Connect establishment timeouts lowered to 3 seconds.
To align with authenticate-plus api latency
Connection pool-time out was unreasonably high (5s), when combined with HTTP connection establishment and HTTP read timeouts would appear to indicate that 15 seconds total was available for authenticate-plus connections. Pool timeout lowered to 1 second as there should always be a connection available from the pool. 
HTTP Connect establishment timeouts lowered as part of a gradual reduction to a more reasonable value.
- [LIME-1175](https://govukverify.atlassian.net/browse/LIME-1175)
[LIME-1175]: https://govukverify.atlassian.net/browse/LIME-1175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …
> LIME-1175 Increase authenticateplus timeout to 6 seconds

- build.gradle
- lambdas/fraudcheck/build.gradle
- lambdas/issuecredential/build.gradle
Upgrading version changes for powertools in build.gradle, and using the same version throughout. AWS Metric version removed so to rely on powertools.
- [LIME-1190](https://govukverify.atlassian.net/browse/LIME-1190)
[LIME-1190]: https://govukverify.atlassian.net/browse/LIME-1190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1190 Update powertools to 1.18.0

- acceptance-tests/src/test/java/gov/di_ipv_fraud/runners/TestRunner.java
- acceptance-tests/src/test/resources/cucumber.properties
Remove cucumber publish variable
A previous PR set the publish value to false to disable the report publishing.
The presence of the variable is however is still being flagged.
- [LIME-1212](https://govukverify.atlassian.net/browse/LIME-1212)
[LIME-1212]: https://govukverify.atlassian.net/browse/LIME-1212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1212 Remove references to cucumber publish

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/handler/FraudHandler.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/handler/FraudHandlerTest.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/fraud/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/fraud/api/handler/IssueCredentialHandlerTest.java
LIME-1114 SessionNotFoundExceptions added to handlers
SessionNotFoundException added to both fraud check and issue credential handlers. Corresponding unit tests also created. 
To ensure scenarios where a user has no session id are identified promptly and the correct error is returned. 
- [LIME-1114](https://govukverify.atlassian.net/browse/LIME-1114)
PR for equivalent changes in passport CRI has been completed [here](https://github.com/govuk-one-login/ipv-cri-uk-passport-api/pull/169)
PR for equivalent changes in dl CRI has been completed [here](https://github.com/govuk-one-login/ipv-cri-dl-api/pull/234)
[LIME-1114]: https://govukverify.atlassian.net/browse/LIME-1114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1114 SessionNotFoundExceptions added to handlers

- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/handler/FraudHandler.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/handler/FraudHandlerTest.java
Issue during testing where an empty value for the session_id header was returning Unexpected server error.
Update CheckPassportHandler.java to use UUID so it catches incorrect strings/special chars
Added UUID check for sessionID in CheckPassportHandler.java
Added unit test for invalid sessionID in CheckPassportHandlerTest.java
- [LIME-1114](https://govukverify.atlassian.net/browse/LIME-1114)
- [LIME-1289](https://govukverify.atlassian.net/browse/LIME-1289)
[LIME-1114]: https://govukverify.atlassian.net/browse/LIME-1114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1289]: https://govukverify.atlassian.net/browse/LIME-1289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIME-1114] added sessionID validation UUID check

- infrastructure/lambda/template.yaml
- lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationRequestMapper.java
- lambdas/fraudcheck/src/test/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationRequestMapperTest.java
Add feature flag to toggle the addition of address details in pep requests
To test if there is any positive or negative impact not setting values for a non-mandatory field, prior to permanent removal.
- [LIME-1280](https://govukverify.atlassian.net/browse/LIME-1280)
[LIME-1280]: https://govukverify.atlassian.net/browse/LIME-1280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1280 Add feature flag to toggle the addition of address details in pep requests

- infrastructure/lambda/template.yaml
Flip feature flag IncludeAddressInPepReq to false for int and production.
- The value false was clicked ops to enable rapid and immediate revert in case of an issue.
- The new value is being mirrored in the template.
- [LIME-XXXX](https://govukverify.atlassian.net/browse/LIME-XXXX)
> LIME-1280 Flip feature flag IncludeAddressInPepReq to false for int and production.
